"""MkDocs hook: regenerate docs/cli.md from the rbt Typer app.

Runs `python -m typer rbt.cli utils docs` before every build so the CLI
reference can never drift from the code. The file is only rewritten when its
content changes, which keeps `mkdocs serve` from rebuild-looping.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

HEADER = """\
<!-- THIS FILE IS GENERATED by docs/_hooks/gen_cli_reference.py at docs build
     time from the rbt Typer app. Edit the CLI help text in src/rbt/cli.py,
     not this file. A committed copy is kept so the page is browsable on
     GitHub; `mkdocs build` refreshes it. -->

# `rbt` CLI Reference

The `rbt` command is the single operational surface of the project — every
setup, import, schema, tile-generation, and maintenance task dispatches
through it. This page is generated from the CLI's own help text at docs build
time, so it is always in sync with the code.

!!! tip "Global options come first"
    Options like `--verbose`, `--debug`, and `--no-log-file` belong to the
    top-level command and must appear **before** the subcommand:
    `rbt --no-log-file tiles --dry-run`.

!!! note "Execution modes"
    `rbt tiles` defaults to the native Python engine. `--mode bash` delegates
    to the deprecated bash generators under `production/tile-generation/` —
    an escape hatch kept until the [parity runbook](parity-runbook.md) retires
    them.

"""


def on_pre_build(config) -> None:  # noqa: ANN001 - mkdocs hook signature
    result = subprocess.run(
        [sys.executable, "-m", "typer", "rbt.cli", "utils", "docs", "--name", "rbt"],
        capture_output=True,
        text=True,
        check=True,
    )
    # Drop the generator's own H1 (we provide our own header).
    body = result.stdout
    if body.startswith("# `rbt`"):
        body = body.split("\n", 1)[1].lstrip("\n")
    content = HEADER + body
    target = Path(config["docs_dir"]) / "cli.md"
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        target.write_text(content, encoding="utf-8")
