{{- if and .Values.cache.setup.enabled (not .Values.cache.setup.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rbt-data-generator.fullname" . }}-setup-cache
  labels:
    {{- include "rbt-data-generator.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.cache.setup.accessMode }}
  resources:
    requests:
      storage: {{ .Values.cache.setup.size | quote }}
  {{- if .Values.cache.setup.storageClassName }}
  storageClassName: {{ .Values.cache.setup.storageClassName | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.cache.osm.enabled (not .Values.cache.osm.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rbt-data-generator.fullname" . }}-osm-cache
  labels:
    {{- include "rbt-data-generator.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.cache.osm.accessMode }}
  resources:
    requests:
      storage: {{ .Values.cache.osm.size | quote }}
  {{- if .Values.cache.osm.storageClassName }}
  storageClassName: {{ .Values.cache.osm.storageClassName | quote }}
  {{- end }}
{{- end }}
