{{- if and .Values.prometheus.enabled .Values.prometheus.persistence.enabled (not .Values.prometheus.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rbt-data-generator.fullname" . }}-prometheus
  labels:
    {{- include "rbt-data-generator.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  accessModes:
    - {{ .Values.prometheus.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size | quote }}
  {{- if .Values.prometheus.persistence.storageClassName }}
  storageClassName: {{ .Values.prometheus.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
