{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rbt-data-generator.fullname" . }}-prometheus
  labels:
    {{- include "rbt-data-generator.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "rbt-data-generator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "rbt-data-generator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      {{- include "rbt-data-generator.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "rbt-data-generator.serviceAccountName" . }}
      {{- with .Values.prometheus.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.registry }}/{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
              readOnly: true
            - name: data
              mountPath: /prometheus
          {{- with .Values.prometheus.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "rbt-data-generator.fullname" . }}-prometheus
        - name: data
          {{- if .Values.prometheus.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.prometheus.persistence.existingClaim }}
          {{- else if .Values.prometheus.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "rbt-data-generator.fullname" . }}-prometheus
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.prometheus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
