{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbt-data-generator.fullname" . }}-prometheus
  labels:
    {{- include "rbt-data-generator.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    {{- include "rbt-data-generator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
{{- end }}
